spring.application.name=taskmanagement-api

server.port=8081

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanagement_db
spring.datasource.username=postgres
spring.datasource.password=qwer

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

app.jwt.secret=8df3a0da3596b08320349e20cefa5c7b66d16ccc61c504d21ca15c0b5ed965e3
app.jwt.expiration=300000